// Auto-generated partner/client logo list for the homepage wall.
// Files live in /public/images/partners/<slug>.png
export type Partner = { slug: string; name: string };

export const partners: Partner[] = [
  { slug: "nestle", name: "Nestle" },
  { slug: "pepsico", name: "PepsiCo" },
  { slug: "mcdonalds", name: "McDonald's" },
  { slug: "honda", name: "Honda" },
  { slug: "shell", name: "Shell" },
  { slug: "telenor", name: "Telenor" },
  { slug: "zong", name: "Zong" },
  { slug: "jazz", name: "Jazz" },
  { slug: "metro", name: "Metro" },
  { slug: "dawlance", name: "Dawlance" },
  { slug: "undp", name: "UNDP" },
  { slug: "save-the-children", name: "Save the Children" },
  { slug: "philip-morris", name: "Philip Morris" },
  { slug: "atlas-honda", name: "Atlas Honda" },
  { slug: "interloop", name: "Interloop" },
  { slug: "sapphire", name: "Sapphire" },
  { slug: "shan-foods", name: "Shan Foods" },
  { slug: "mobilink-bank", name: "Mobilink Bank" },
  { slug: "sui-northern-gas", name: "Sui Northern Gas" },
  { slug: "reon-energy", name: "Reon Energy" },
  { slug: "lums", name: "LUMS" },
  { slug: "icap", name: "ICAP" },
  { slug: "cesvi", name: "CESVI" },
  { slug: "right-to-play", name: "Right to Play" },
  { slug: "soorty", name: "Soorty" },
  { slug: "atlas-copco", name: "Atlas Copco" },
  { slug: "3pol", name: "3POL" },
  { slug: "almirah", name: "Almirah" },
  { slug: "alphalabs", name: "AlphaLabs" },
  { slug: "bkk", name: "BKK" },
  { slug: "bullseye-communications", name: "Bullseye Communications" },
  { slug: "cppa", name: "CPPA" },
  { slug: "cyclone-agency", name: "Cyclone Agency" },
  { slug: "gar-agribusiness-and-food", name: "GAR Agribusiness & Food" },
  { slug: "iap-institute-of-architects-pakistan", name: "Institute of Architects Pakistan" },
  { slug: "ink-factory", name: "Ink Factory" },
  { slug: "jcm-power", name: "JCM Power" },
  { slug: "lumovy", name: "Lumovy" },
  { slug: "mari-energies", name: "Mari Energies" },
  { slug: "masons-coffee-and-bake-shop", name: "Masoom's Coffee & Bake Shop" },
  { slug: "nlc-national-logistics-cell", name: "NLC \u2014 National Logistics Cell" },
  { slug: "paperclip", name: "Paperclip" },
  { slug: "pegasync", name: "PegaSync" },
  { slug: "relife", name: "RELIFE" },
  { slug: "sentiments-express", name: "Sentiments Express" },
  { slug: "spectreco", name: "Spectreco" },
  { slug: "ted", name: "TED" },
  { slug: "the-aster-school", name: "The Aster School" },
  { slug: "the-ivy-school", name: "The Ivy School" },
  { slug: "visual-works", name: "Visual Works" },
  { slug: "weatherwalay", name: "Weatherwalay" },
];
