import type { Product } from "./types";

// NOTE: prices are placeholders for the productized SKUs (confirm before launch).
// Purchasable = fixed-price standard items (checkout). Everything custom/bulk
// routes to Request-a-Quote, per the strategy.

export const products: Product[] = [
  // ---------- Purchasable standard SKUs ----------
  {
    slug: "sample-kit",
    name: "Plantable Sample Kit",
    tagline: "Samples + a 15-min consult before you commit to bulk",
    description:
      "The smartest first step. Get seed-paper swatches, printing and embossing examples, and card/tag/calendar format samples in your hands — plus a 15-minute consultation. The kit price is adjusted against your first bulk order.",
    category: "seed-paper",
    segments: ["csr-corporate-gifts", "plantable-brand-materials", "weddings-events"],
    purchasable: true,
    price: 3500,
    leadTime: "Ships in 2–3 working days",
    features: [
      "Seed-paper + biodegradable stock swatches",
      "Print, embossing & finishing examples",
      "Card, tag & calendar format samples",
      "15-minute consultation",
      "Kit price adjusted against your bulk order",
    ],
    image: "/images/products/product-spread-grass.jpg",
    featured: true,
    seo: {
      seoTitle: "Plantable Seed Paper Sample Kit — Boxit Pakistan",
      metaDescription:
        "Order Boxit's plantable seed paper sample kit: seed-paper swatches, print & finishing examples, and a consult. Cost adjusted against your bulk order.",
      keywords: [
        "seed paper sample kit",
        "plantable paper samples Pakistan",
        "seed paper test pack",
      ],
    },
  },
  {
    slug: "seed-paper-a5-pack",
    name: "Seed Paper A5 Pack (25 sheets)",
    tagline: "Plantable A5 sheets for cards, notes & DIY",
    description:
      "Tree-free, seed-embedded A5 sheets you can print, write or craft on, then plant. Grows into herbs and wildflowers. Great for testing before a bulk run.",
    category: "seed-paper",
    segments: ["seed-paper-stock", "weddings-events"],
    image: "/images/products/seed-paper-a5-printed.jpg",
    gallery: [
      "/images/products/seed-paper-a5-printed.jpg",
      "/images/products/seed-paper-a5-printed-cards.jpg",
    ],
    purchasable: true,
    price: 1200,
    moq: "1 pack",
    leadTime: "Ships in 2–3 working days",
    features: ["25 × A5 seed paper sheets", "Mixed herb / wildflower seeds", "Tree-free, 100% biodegradable"],
  },
  {
    slug: "plantable-greeting-cards-set",
    name: "Plantable Greeting Cards (Set of 10)",
    tagline: "Cards that grow into flowers",
    description:
      "Ten blank plantable greeting cards with envelopes. Write your message, gift it, then plant the card. Ideal for personal gifting and small businesses.",
    category: "cards-stationery",
    segments: ["csr-corporate-gifts", "weddings-events"],
    image: "/images/products/greeting-cards-spread.png",
    gallery: [
      "/images/products/greeting-cards-spread.png",
      "/images/products/greeting-cards-1.jpg",
    ],
    purchasable: true,
    price: 1500,
    moq: "1 set",
    leadTime: "Ships in 2–3 working days",
    features: ["10 cards + 10 envelopes", "Blank inside", "Plant-and-grow instruction card included"],
  },
  {
    slug: "custom-seed-balls-bulk",
    name: "Custom Seed Balls (Bulk)",
    tagline: "Wildflower seed bombs for large giveaways",
    description:
      "Bulk wildflower seed balls for CSR drives, events and corporate giveaways — just toss in soil and water. Add custom-printed pouches to brand them.",
    category: "seed-balls",
    segments: ["csr-corporate-gifts", "weddings-events"],
    image: "/images/products/seed-balls-bkk.jpg",
    purchasable: false,
    moq: "From 500 balls",
    leadTime: "5–10 working days",
    features: ["Wildflower seed mix", "Bulk packed", "Optional branded pouches"],
  },
  {
    slug: "plantable-bookmarks",
    name: "Plantable Bookmarks (Set of 10)",
    tagline: "Read it, then grow it",
    description:
      "Seed-paper bookmarks that grow into herbs once you're done with them. A low-cost, high-delight giveaway.",
    category: "cards-stationery",
    segments: ["csr-corporate-gifts"],
    image: "/images/products/tags-bookmarks-1.jpg",
    purchasable: true,
    price: 800,
    moq: "1 set",
    leadTime: "Ships in 2–3 working days",
    features: ["10 seed-paper bookmarks", "Basil / mixed herb seeds"],
  },
  {
    slug: "blank-seed-paper-tags",
    name: "Blank Seed Paper Tags (50 pcs)",
    tagline: "Plantable hang tags, ready to brand",
    description:
      "Pre-cut blank seed-paper hang tags with string. Stamp or print your own, or order custom-printed in bulk.",
    category: "tags-inserts",
    segments: ["plantable-brand-materials"],
    image: "/images/products/tags-bookmarks-2.jpg",
    purchasable: true,
    price: 1000,
    moq: "1 pack of 50",
    leadTime: "Ships in 2–3 working days",
    features: ["50 pre-cut tags + string", "Plantable seed paper", "Custom printing available in bulk"],
  },

  // ---------- Custom / bulk → Request a quote ----------
  {
    slug: "custom-shopping-bags",
    name: "Custom Plantable Shopping Bags",
    tagline: "Your retail bag, biodegradable and brandable",
    description:
      "Custom-sized shopping bags in our biodegradable / seed-paper stock, printed with your logo and brand colours. The first offline ad your customer carries home.",
    category: "bags-sleeves",
    segments: ["plantable-brand-materials"],
    image: "/images/products/shopping-bag-metro.jpg",
    purchasable: false,
    moq: "From 200 bags",
    leadTime: "7–12 working days after approval",
    features: ["Custom size & handle", "Logo + brand-colour printing", "Multiple GSM/thickness options"],
    featured: true,
    seo: {
      keywords: [
        "custom shopping bags Pakistan",
        "biodegradable shopping bags",
        "plantable retail bags Pakistan",
      ],
    },
  },
  {
    slug: "seed-paper-petal-bags",
    name: "Seed Paper & Petal Bags",
    tagline: "Decorative plantable bags — plant them, watch them grow",
    description:
      "Colourful seed-paper and petal-embedded gift bags with contrast rope handles. A decorative plantable bag for retail, favours and gifting — the whole bag plants into flowers.",
    category: "bags-sleeves",
    segments: ["plantable-brand-materials", "weddings-events"],
    image: "/images/products/petal-bags-colorful.jpg",
    purchasable: false,
    moq: "From 200 bags",
    leadTime: "7–12 working days after approval",
    features: ["Seed-paper / petal stock", "Contrast rope handles", "Custom size & colours"],
  },
  {
    slug: "plantable-gift-bags",
    name: "Plantable Gift Bags",
    tagline: "Small plantable gift & favour bags, printed with your message",
    description:
      "Compact plantable gift bags for giveaways, event favours and small retail items — custom-printed with your artwork and rope handles. Recipients plant the bag when they're done.",
    category: "bags-sleeves",
    segments: ["plantable-brand-materials", "csr-corporate-gifts"],
    image: "/images/products/bag-sunshine-blue.jpg",
    purchasable: false,
    moq: "From 200 bags",
    leadTime: "7–12 working days after approval",
    features: ["Custom print & message", "Rope handles", "Seed-paper stock"],
  },
  {
    slug: "plantable-paper-bags",
    name: "Plantable Paper Bags",
    tagline: "Kraft-style plantable bags with a printed plant-me guide",
    description:
      "Natural kraft-look plantable paper bags printed with your logo and a friendly 'how to plant it' guide — a self-explaining sustainability statement for retail, gifting and events.",
    category: "bags-sleeves",
    segments: ["plantable-brand-materials", "csr-corporate-gifts"],
    image: "/images/products/bag-unwomen.jpg",
    purchasable: false,
    moq: "From 200 bags",
    leadTime: "7–12 working days after approval",
    features: ["Custom logo + plant-guide print", "Rope handles", "Seed-paper stock"],
  },
  {
    slug: "event-campaign-bags",
    name: "Event & Campaign Bags",
    tagline: "Plantable bags for launches, awareness days and CSR events",
    description:
      "Plantable event bags printed for a specific campaign, awareness day or launch — carry the giveaway home, then plant the bag. A memorable, on-brand keepsake for attendees.",
    category: "bags-sleeves",
    segments: ["csr-corporate-gifts", "plantable-brand-materials"],
    image: "/images/products/bag-world-env.jpg",
    purchasable: false,
    moq: "From 200 bags",
    leadTime: "7–12 working days after approval",
    features: ["Campaign / event print", "Rope handles", "Seed-paper stock"],
  },
  {
    slug: "branded-kraft-bags",
    name: "Branded Kraft Shopping Bags",
    tagline: "Landscape kraft retail bags printed with your brand",
    description:
      "Wide, landscape-format plantable kraft shopping bags for retail and corporate gifting — printed with your logo and a plant-me guide, with rope handles. The bag becomes a plant.",
    category: "bags-sleeves",
    segments: ["plantable-brand-materials", "csr-corporate-gifts"],
    image: "/images/products/bag-wed.jpg",
    purchasable: false,
    moq: "From 200 bags",
    leadTime: "7–12 working days after approval",
    features: ["Landscape format", "Logo + plant-guide print", "Rope handles"],
  },
  {
    slug: "plantable-bag-range",
    name: "Plantable Bag Range",
    tagline: "Our custom plantable bags, made to your brand",
    description:
      "A snapshot of our plantable bag range — different sizes, prints and finishes, all custom-made on seed-paper stock. Tell us your size, artwork and quantity and we'll build yours.",
    category: "bags-sleeves",
    segments: ["plantable-brand-materials", "csr-corporate-gifts", "weddings-events"],
    image: "/images/products/bag-range.jpg",
    purchasable: false,
    moq: "From 200 bags",
    leadTime: "7–12 working days after approval",
    features: ["Any size & format", "Full custom printing", "Seed-paper stock"],
  },
  {
    slug: "corporate-plantable-bags",
    name: "Corporate & Institutional Bags",
    tagline: "Plantable bags for corporate, NGO and institutional campaigns",
    description:
      "Plantable seed-paper bags printed for corporate, development and institutional partners — logo, message and a plant-me guide in your brand colours. Carry the giveaway, then plant the bag.",
    category: "bags-sleeves",
    segments: ["csr-corporate-gifts", "plantable-brand-materials"],
    image: "/images/products/secp-unwomen-bag.jpg",
    purchasable: false,
    moq: "From 200 bags",
    leadTime: "7–12 working days after approval",
    features: ["Logo + plant-guide print", "Rope handles", "Seed-paper stock"],
  },
  {
    slug: "plantable-giveaway-bags",
    name: "Plantable Giveaway Bags",
    tagline: "Kraft giveaway bags with a printed sustainability note",
    description:
      "Natural kraft-look plantable giveaway bags with a printed sustainability message and plant-me guide — a self-explaining, on-brand keepsake for corporate gifting and events.",
    category: "bags-sleeves",
    segments: ["csr-corporate-gifts", "plantable-brand-materials"],
    image: "/images/products/gar-bag-1.jpg",
    gallery: [
      "/images/products/gar-bag-1.jpg",
      "/images/products/gar-bag-2.jpg",
    ],
    purchasable: false,
    moq: "From 200 bags",
    leadTime: "7–12 working days after approval",
    features: ["Sustainability-note print", "Twine handles", "Seed-paper stock"],
  },
  {
    slug: "seed-paper-sheets-bulk",
    name: "Seed Paper Sheets — Bulk (A4)",
    tagline: "Plantable stock for your production run",
    description:
      "Bulk A4 plantable seed-paper sheets for your own printing and converting. Choose GSM, seed type and quantity.",
    category: "seed-paper",
    segments: ["seed-paper-stock"],
    image: "/images/products/seed-paper-sheets-colored-fan.jpg",
    gallery: [
      "/images/products/seed-paper-sheets-colored-fan.jpg",
      "/images/products/seed-paper-sheets-stack.jpg",
    ],
    purchasable: false,
    moq: "From 300 A4 sheets",
    leadTime: "5–10 working days",
    features: ["GSM/thickness options", "Seed selection (seasonal)", "Largest stock size 15\" × 20\" deckle edge"],
  },
  {
    slug: "plantable-business-cards",
    name: "Plantable Business Cards",
    tagline: "A business card that grows into a plant",
    description:
      "Custom plantable business cards printed with your brand. Most business cards get binned — yours gets planted.",
    category: "cards-stationery",
    segments: ["plantable-brand-materials", "csr-corporate-gifts"],
    image: "/images/products/agha-steel-invite.png",
    gallery: [
      "/images/products/agha-steel-invite.png",
      "/images/products/ejad-tech-summit-a.png",
      "/images/products/ejad-tech-summit-b.png",
    ],
    purchasable: false,
    moq: "From 1,200 cards",
    leadTime: "5–8 working days",
    features: ["Custom print, both sides", "Seed selection", "Optional embossing"],
  },
  {
    slug: "seed-paper-calendars",
    name: "Plantable Calendars",
    tagline: "A desk calendar your clients can plant page by page",
    description:
      "Custom seed-paper calendars for corporate gifting and CSR campaigns — each page plants into herbs or flowers.",
    category: "corporate",
    segments: ["csr-corporate-gifts"],
    image: "/images/products/calendars-fan-easel.png",
    gallery: [
      "/images/products/calendars-fan-easel.png",
      "/images/products/calendars-1.jpg",
    ],
    purchasable: false,
    moq: "From 200 calendars",
    leadTime: "10–15 working days",
    features: ["Custom design & branding", "Desk or wall formats", "Plantable pages"],
    featured: true,
  },
  {
    slug: "plantable-desk-calendar",
    name: "Plantable Desk Calendar",
    tagline: "A tear-off desk calendar on a wooden easel — plant each month",
    description:
      "A standing monthly desk calendar with a mini wooden easel — each printed page tears off and plants into herbs or flowers. A year of desk-side branding your clients can grow.",
    category: "corporate",
    segments: ["csr-corporate-gifts"],
    image: "/images/products/desk-calendar-easel.png",
    purchasable: false,
    moq: "From 200 calendars",
    leadTime: "10–15 working days",
    features: ["Monthly tear-off pages", "Mini wooden easel stand", "Custom photo & branding"],
  },
  {
    slug: "seed-paper-desk-calendar",
    name: "Seed Paper Desk Calendar",
    tagline: "Mini seed-paper easel calendar for premium corporate gifting",
    description:
      "A compact seed-paper desk calendar on a mini easel — printed on our textured plantable stock with custom art per month. A tactile, premium giveaway that plants after the year is out.",
    category: "corporate",
    segments: ["csr-corporate-gifts"],
    image: "/images/products/seed-paper-calendars-easel.png",
    purchasable: false,
    moq: "From 200 calendars",
    leadTime: "10–15 working days",
    features: ["Seed-paper plantable pages", "Mini easel stand", "Custom monthly artwork"],
  },
  {
    slug: "plantable-diaries",
    name: "Plantable Diaries (A5)",
    tagline: "A5 diaries with plantable outer seed-paper covers",
    description:
      "Branded A5 diaries with plantable seed-paper outer covers — premium corporate gifting your clients can plant when the year is over.",
    category: "corporate",
    segments: ["csr-corporate-gifts"],
    image: "/images/products/diary-1.jpg",
    purchasable: false,
    moq: "From 300 units",
    leadTime: "10–15 working days",
    features: ["A5 format", "Outer seed-paper cover", "Custom branding & paper-stock options"],
  },
  {
    slug: "plantable-notebooks",
    name: "Plantable Notebooks",
    tagline: "Notebooks with plantable outer seed-paper covers",
    description:
      "Custom notebooks with plantable seed-paper outer covers and your branding — a practical, lower-cost alternative to the A5 diary for larger gifting runs.",
    category: "corporate",
    segments: ["csr-corporate-gifts"],
    image: "/images/products/plantable-notebook-eco-pen.jpg",
    gallery: [
      "/images/products/plantable-notebook-eco-pen.jpg",
      "/images/products/lumovy-notebook.jpg",
      "/images/products/jazzworld-notebook.jpg",
    ],
    purchasable: false,
    moq: "From 300 units",
    leadTime: "10–15 working days",
    features: ["Outer seed-paper cover", "Custom branding", "Paper-stock options"],
  },
  {
    slug: "branded-sleeves-inserts",
    name: "Branded Sleeves & Inserts",
    tagline: "Thank-you cards, sleeves & inserts that grow",
    description:
      "Custom plantable sleeves, inserts and thank-you cards for cosmetics, wellness and retail brands — match your unboxing to your values.",
    category: "tags-inserts",
    segments: ["plantable-brand-materials"],
    image: "/images/products/knisa-thankyou-a.png",
    gallery: [
      "/images/products/knisa-thankyou-a.png",
      "/images/products/knisa-thankyou-b.png",
      "/images/products/knisa-thankyou-c.png",
      "/images/products/knisa-thankyou-d.png",
    ],
    purchasable: false,
    moq: "From 500 units",
    leadTime: "7–10 working days",
    features: ["Custom size & print", "Seed-paper or biodegradable stock", "Care-card / instruction printing"],
  },
  {
    slug: "wedding-invitations",
    name: "Plantable Wedding Invitations",
    tagline: "An invitation that grows after the wedding",
    description:
      "Custom plantable invitations and envelopes — guests plant the card and remember your day every time it blooms.",
    category: "event",
    segments: ["weddings-events"],
    image: "/images/products/walima-invites.png",
    purchasable: false,
    moq: "From 300–500 sets",
    leadTime: "10–15 working days",
    features: ["Custom design & print", "Matching envelopes & tags", "Seed selection"],
    featured: true,
  },
  {
    slug: "plantable-invitation-cards",
    name: "Plantable Invitation Cards",
    tagline: "Seed-paper cards for weddings & celebrations",
    description:
      "Custom plantable invitation and event cards — printed with your design and foliage motifs, then planted as a living keepsake after the occasion.",
    category: "event",
    segments: ["weddings-events"],
    image: "/images/products/wedding-cards-1.jpg",
    purchasable: false,
    moq: "From 300 cards",
    leadTime: "10–15 working days",
    features: ["Custom design & print", "Matching envelopes", "Seed selection"],
  },
  {
    slug: "plantable-confetti",
    name: "Plantable Confetti & Giveaways",
    tagline: "Celebrate without the plastic",
    description:
      "Biodegradable seed-paper confetti, favours and giveaways for weddings, launches and events.",
    category: "event",
    segments: ["weddings-events", "csr-corporate-gifts"],
    image: "/images/products/confetti-giveaways-cards.jpg",
    purchasable: false,
    moq: "From 50 packs",
    leadTime: "5–10 working days",
    features: ["Seed-paper confetti", "Custom favour packaging", "Event branding"],
  },
  {
    slug: "hang-tags-price-tags",
    name: "Custom Hang Tags & Price Tags",
    tagline: "Plantable tags printed with your brand",
    description:
      "Custom-printed seed-paper hang tags and price tags for fashion and retail — durable enough to hang, plantable when removed.",
    category: "tags-inserts",
    segments: ["plantable-brand-materials"],
    image: "/images/products/tags-bookmarks-1.jpg",
    purchasable: false,
    moq: "From 500 tags",
    leadTime: "7–10 working days",
    features: ["Custom shape & size", "Logo printing", "String/eyelet options"],
  },
  {
    slug: "client-branded-hang-tags",
    name: "Branded Hang Tags — Client Work",
    tagline: "Real seed-paper hang tags we've printed for brands",
    description:
      "A showcase of custom plantable hang tags produced for retail and lifestyle brands — printed on seed paper with logos, plant-me instructions and twine. Tear and plant after use.",
    category: "tags-inserts",
    segments: ["plantable-brand-materials"],
    image: "/images/products/hang-tags-branded-1.jpg",
    gallery: [
      "/images/products/hang-tags-branded-1.jpg",
      "/images/products/hang-tags-branded-2.jpg",
      "/images/products/hang-tags-branded-3.jpg",
    ],
    purchasable: false,
    moq: "From 500 tags",
    leadTime: "7–10 working days",
    features: ["Custom shape & print", "Twine / eyelet options", "Plant-me instructions"],
  },
  {
    slug: "plantable-event-invitations",
    name: "Plantable Event Invitations",
    tagline: "Seed-paper invites with matching plantable envelopes",
    description:
      "Custom plantable invitation cards with seed-paper envelopes — for weddings, valimas and events. Printed with your artwork and a plant-me guide; guests plant the card and it grows.",
    category: "event",
    segments: ["plantable-brand-materials", "weddings-events"],
    image: "/images/products/branded-insert-invite.jpg",
    purchasable: false,
    moq: "From 300 invites",
    leadTime: "10–15 working days",
    features: ["Custom artwork & print", "Matching seed-paper envelope", "Plant-me instruction print"],
  },
  {
    slug: "corporate-plantable-cards",
    name: "Corporate Plantable Cards",
    tagline: "Branded greeting, event & CSR cards that grow",
    description:
      "Custom plantable greeting cards, event invites and CSR message cards for corporates — printed on seed paper with your branding. Recipients plant them into herbs and wildflowers.",
    category: "cards-stationery",
    segments: ["plantable-brand-materials", "csr-corporate-gifts"],
    image: "/images/products/branded-inserts-corporate.jpg",
    purchasable: false,
    moq: "From 300 cards",
    leadTime: "10–15 working days",
    features: ["Custom branding & print", "Folded or flat formats", "Plant-me instructions"],
  },
  {
    slug: "seed-paper-coasters",
    name: "Plantable Seed Paper Coasters",
    tagline: "Coasters that grow into herbs when you're done with them",
    description:
      "Custom-printed circular or square seed-paper coasters — a conversation piece at every event table. Use them, then plant them.",
    category: "event",
    segments: ["csr-corporate-gifts", "weddings-events"],
    image: "/images/products/coasters-1.jpg",
    purchasable: false,
    moq: "From 500 coasters",
    leadTime: "7–10 working days",
    features: [
      "Custom print (logo, event date, message)",
      "Circle or square format",
      "Wildflower or herb seed selection",
    ],
    seo: {
      seoTitle: "Plantable Seed Paper Coasters — Custom Branded Pakistan",
      metaDescription:
        "Custom seed-paper coasters that grow into plants after use. Ideal for corporate events, weddings and CSR gifting. Made in Pakistan.",
      keywords: ["plantable coasters Pakistan", "seed paper coasters", "eco coasters corporate"],
    },
  },
  {
    slug: "plantable-pennants",
    name: "Plantable Pennants",
    tagline: "Decorative pennants you hang, then plant",
    description:
      "Seed-paper pennants in custom shapes and sizes — great for product launches, events and store décor. After the event, guests take them home and plant them.",
    category: "event",
    segments: ["weddings-events", "plantable-brand-materials"],
    image: "/images/products/pennants-1.jpg",
    purchasable: false,
    moq: "From 500 pennants",
    leadTime: "7–10 working days",
    features: [
      "Custom shape, size and print",
      "String/twine included",
      "Mixed herb or wildflower seeds",
    ],
    seo: {
      seoTitle: "Plantable Pennants — Seed Paper Event Decor Pakistan",
      metaDescription:
        "Custom seed-paper pennants for events, launches and brand décor. Guests take them home and plant them. Made in Pakistan.",
      keywords: ["plantable pennants Pakistan", "seed paper pennants", "eco event decor Pakistan"],
    },
  },

  // ---------- Added to cover every item in the instant estimator ----------
  // MOQ + lead time mirror src/content/estimator.ts (the pricing-sheet source).

  // Seed Paper & Sheets
  {
    slug: "deckle-edge-seed-paper",
    name: "Deckle Edge Seed Paper",
    tagline: "Hand-torn plantable sheets with a premium raw edge",
    description:
      "Deckle-edge seed-paper sheets with a natural, hand-torn border — the premium stock for invitations, certificates and luxury stationery. Plants into herbs and wildflowers.",
    category: "seed-paper",
    segments: ["seed-paper-stock", "weddings-events"],
    image: "/images/products/seed-paper-sheets-stack.jpg",
    purchasable: false,
    moq: "From 300 sheets",
    leadTime: "7–10 working days",
    features: ["Natural deckle (torn) edge", "Seed selection (seasonal)", "Also available without seeds"],
  },
  {
    slug: "neem-leaf-paper",
    name: "Neem Leaf Paper",
    tagline: "Handmade sheets with real embedded neem leaves",
    description:
      "Tree-free handmade paper with real pressed neem leaves suspended in the sheet — a natural botanical texture for invitations, menus and premium stationery. Each sheet is one of a kind.",
    category: "seed-paper",
    segments: ["seed-paper-stock", "weddings-events"],
    image: "/images/products/deckle-edge-neem-1.jpg",
    gallery: [
      "/images/products/deckle-edge-neem-1.jpg",
      "/images/products/deckle-edge-neem-2.jpg",
    ],
    purchasable: false,
    moq: "From 300 sheets",
    leadTime: "7–10 working days",
    features: ["Real embedded neem leaves", "Natural deckle (torn) edge", "Tree-free & biodegradable"],
  },
  {
    slug: "deckle-edge-paper",
    name: "Deckle Edge Paper (No Seeds)",
    tagline: "Tree-free deckle-edge stock, without embedded seeds",
    description:
      "The same hand-torn deckle edge in our tree-free, biodegradable paper — for brands that want the premium look without the plantable feature. Lower cost than seed paper.",
    category: "seed-paper",
    segments: ["seed-paper-stock", "plantable-brand-materials"],
    image: "/images/products/deckle-edge-no-seeds-blank.jpg",
    purchasable: false,
    moq: "From 300 sheets",
    leadTime: "7–10 working days",
    features: ["Natural deckle (torn) edge", "Tree-free & biodegradable", "No seeds — lower cost"],
  },
  {
    slug: "cotton-paper",
    name: "Cotton Paper",
    tagline: "Soft, durable tree-free cotton-rag stock",
    description:
      "Premium cotton-rag paper — tree-free, biodegradable and beautifully textured for letterpress, certificates and high-end print. The lowest MOQ in our sheet range.",
    category: "seed-paper",
    segments: ["seed-paper-stock", "plantable-brand-materials"],
    image: "/images/products/cotton-paper-rag-trio.png",
    purchasable: false,
    moq: "From 100 sheets",
    leadTime: "7–10 working days",
    features: ["100% cotton-rag stock", "Tree-free & biodegradable", "Takes letterpress & foil well"],
  },

  // Cards & Stationery
  {
    slug: "plantable-envelopes",
    name: "Plantable Envelopes",
    tagline: "Flap or v-shape envelopes that grow when planted",
    description:
      "Custom seed-paper envelopes in flap or v-shape formats to match your invitations, cards and mailers. Recipients plant the envelope instead of binning it.",
    category: "cards-stationery",
    segments: ["weddings-events", "plantable-brand-materials"],
    image: "/images/products/plantable-envelopes-blue-1.jpg",
    gallery: [
      "/images/products/plantable-envelopes-blue-1.jpg",
      "/images/products/plantable-envelopes-blue-2.jpg",
      "/images/products/plantable-envelopes-blue-3.jpg",
    ],
    purchasable: false,
    moq: "From 300 envelopes",
    leadTime: "7–10 working days",
    features: ["Flap or v-shape format", "Custom print & size", "Seed selection (seasonal)"],
  },
  {
    slug: "plantable-brochures",
    name: "Plantable Brochures",
    tagline: "Marketing brochures that plant into flowers",
    description:
      "Seed-paper brochures and flyers printed with your campaign — the print collateral that never ends up as landfill. Great for launches, expos and CSR drives.",
    category: "cards-stationery",
    segments: ["plantable-brand-materials", "csr-corporate-gifts"],
    image: "/images/products/greeting-cards-1.jpg",
    purchasable: false,
    moq: "From 500 brochures",
    leadTime: "7–10 working days",
    features: ["Custom fold & print", "Seed-paper stock", "Herb or wildflower seeds"],
  },
  {
    slug: "plantable-letterheads",
    name: "Plantable Letterheads",
    tagline: "Branded letterheads on seed paper",
    description:
      "Custom-printed seed-paper letterheads that carry your correspondence and, once done, plant into herbs and flowers — a sustainability statement on every page.",
    category: "cards-stationery",
    segments: ["plantable-brand-materials", "csr-corporate-gifts"],
    image: "/images/products/letterhead-usaid-linen.png",
    purchasable: false,
    moq: "From 500 sheets",
    leadTime: "7–10 working days",
    features: ["Custom brand printing", "Seed-paper or biodegradable stock", "Matching envelopes available"],
  },
  {
    slug: "plantable-ball-points",
    name: "Plantable Ball Points",
    tagline: "Seeded pens that grow after their last drop of ink",
    description:
      "Biodegradable ball-point pens with a seed capsule — a branded giveaway that plants into herbs or flowers instead of adding to plastic waste.",
    category: "cards-stationery",
    segments: ["csr-corporate-gifts", "plantable-brand-materials"],
    image: "/images/products/ballpoint-kraft-a.png",
    gallery: [
      "/images/products/ballpoint-kraft-a.png",
      "/images/products/ballpoint-kraft-b.png",
      "/images/products/ballpoint-newspaper-wall.png",
      "/images/products/ballpoint-box.png",
    ],
    purchasable: false,
    moq: "From 300 ball points",
    leadTime: "7–10 working days",
    features: ["Seed capsule end-cap", "Custom logo printing", "Biodegradable barrel"],
  },
  {
    slug: "plantable-pencils",
    name: "Plantable Pencils",
    tagline: "Seeded pencils you plant when they're too short to use",
    description:
      "Wooden pencils with a seed capsule on the end — write with them, then plant the stub to grow herbs or flowers. A favourite CSR and event giveaway.",
    category: "cards-stationery",
    segments: ["csr-corporate-gifts", "plantable-brand-materials"],
    image: "/images/products/newspaper-pencils-wall.png",
    gallery: [
      "/images/products/newspaper-pencils-wall.png",
      "/images/products/newspaper-pencils-bagged.png",
      "/images/products/newspaper-pencils-closeup.png",
    ],
    purchasable: false,
    moq: "From 300 pencils",
    leadTime: "7–10 working days",
    features: ["Seed capsule on the end", "Custom logo engraving", "Herb / flower seed options"],
  },

  // Weddings & Events
  {
    slug: "seed-ball-pouches",
    name: "Pouches for Seed Balls",
    tagline: "Branded pouches to package your seed balls",
    description:
      "Custom-printed pouches sized for our wildflower seed balls — the finishing touch for giveaways, favours and CSR kits. Pair with the Seed Balls Jar or a bulk seed-ball run.",
    category: "seed-balls",
    segments: ["csr-corporate-gifts", "weddings-events"],
    image: "/images/products/seed-balls-1.jpg",
    purchasable: false,
    moq: "From 250 pouches",
    leadTime: "5–10 working days",
    features: ["Sized for seed balls", "Custom print & branding", "Seed-paper or biodegradable stock"],
  },
  {
    slug: "plantable-event-stationery",
    name: "Plantable Events Cards",
    tagline: "Menus, place cards & signage that guests can plant",
    description:
      "Custom seed-paper event stationery — menus, place cards, table numbers and signage — printed for your event and plantable as a keepsake afterwards.",
    category: "event",
    segments: ["weddings-events", "csr-corporate-gifts"],
    image: "/images/products/event-stationery-cards.jpg",
    purchasable: false,
    moq: "From 500 items",
    leadTime: "7–10 working days",
    features: ["Menus, place cards, signage", "Custom design & print", "Herb / wildflower seeds"],
  },

  // Calendars, Diaries & Corporate
  {
    slug: "corporate-souvenir-set-economical",
    name: "Corporate Souvenir Set — Economical",
    tagline: "An entry-level plantable gift set for large runs",
    description:
      "A curated, budget-friendly plantable souvenir set — a mix of seed-paper stationery and giveaways branded for your campaign. Built for high-volume corporate gifting.",
    category: "corporate",
    segments: ["csr-corporate-gifts"],
    image: "/images/products/product-spread-grass.jpg",
    purchasable: false,
    moq: "From 200 sets",
    leadTime: "10–15 working days",
    features: ["Curated plantable items", "Campaign branding", "Bulk delivery planning"],
  },
  {
    slug: "corporate-souvenir-set-executive",
    name: "Corporate Souvenir Set — Executive",
    tagline: "A mid-tier plantable gift set for client gifting",
    description:
      "A step up from Economical — a richer plantable souvenir set with premium seed-paper stationery and a branded box, ideal for client and partner gifting.",
    category: "corporate",
    segments: ["csr-corporate-gifts"],
    image: "/images/products/sample-kit-spread.jpg",
    purchasable: false,
    moq: "From 100 sets",
    leadTime: "10–15 working days",
    features: ["Premium plantable items", "Branded gift box", "Campaign messaging"],
  },
  {
    slug: "corporate-souvenir-set-premium",
    name: "Corporate Souvenir Set — Premium",
    tagline: "Our top-tier plantable souvenir set",
    description:
      "The flagship plantable souvenir set — our most premium seed-paper diary, calendar and gifting pieces in a fully branded box, for high-value corporate recipients.",
    category: "corporate",
    segments: ["csr-corporate-gifts"],
    image: "/images/products/product-spread-grass.jpg",
    purchasable: false,
    moq: "From 100 sets",
    leadTime: "10–15 working days",
    features: ["Flagship plantable pieces", "Fully branded presentation box", "White-glove delivery planning"],
    featured: true,
  },
];
