import type { Product } from "./types";

// NOTE: prices are placeholders for the productized SKUs (confirm before launch).
// Purchasable = fixed-price standard items (checkout). Everything custom/bulk
// routes to Request-a-Quote, per the strategy.

export const products: Product[] = [
  // ---------- Purchasable standard SKUs ----------
  {
    slug: "sample-kit",
    name: "Plantable Sample Kit",
    tagline: "Samples + a 15-min consult before you commit to bulk",
    description:
      "The smartest first step. Get seed-paper swatches, printing and embossing examples, and card/tag/calendar format samples in your hands — plus a 15-minute consultation. The kit price is adjusted against your first bulk order.",
    category: "seed-paper",
    segments: ["csr-corporate-gifts", "plantable-brand-materials", "weddings-events"],
    purchasable: true,
    price: 3500,
    leadTime: "Ships in 2–3 working days",
    features: [
      "Seed-paper + biodegradable stock swatches",
      "Print, embossing & finishing examples",
      "Card, tag & calendar format samples",
      "15-minute consultation",
      "Kit price adjusted against your bulk order",
    ],
    image: "/images/products/product-spread-grass.jpg",
    featured: true,
    seo: {
      seoTitle: "Plantable Seed Paper Sample Kit — Boxit Pakistan",
      metaDescription:
        "Order Boxit's plantable seed paper sample kit: seed-paper swatches, print & finishing examples, and a consult. Cost adjusted against your bulk order.",
      keywords: [
        "seed paper sample kit",
        "plantable paper samples Pakistan",
        "seed paper test pack",
      ],
    },
  },
  {
    slug: "seed-paper-a5-pack",
    name: "Seed Paper A5 Pack (25 sheets)",
    tagline: "Plantable A5 sheets for cards, notes & DIY",
    description:
      "Tree-free, seed-embedded A5 sheets you can print, write or craft on, then plant. Grows into herbs and wildflowers. Great for testing before a bulk run.",
    category: "seed-paper",
    segments: ["seed-paper-stock", "weddings-events"],
    image: "/images/products/artistic-sheets-1.jpg",
    purchasable: true,
    price: 1200,
    moq: "1 pack",
    leadTime: "Ships in 2–3 working days",
    features: ["25 × A5 seed paper sheets", "Mixed herb / wildflower seeds", "Tree-free, 100% biodegradable"],
  },
  {
    slug: "plantable-greeting-cards-set",
    name: "Plantable Greeting Cards (Set of 10)",
    tagline: "Cards that grow into flowers",
    description:
      "Ten blank plantable greeting cards with envelopes. Write your message, gift it, then plant the card. Ideal for personal gifting and small businesses.",
    category: "cards-stationery",
    segments: ["csr-corporate-gifts", "weddings-events"],
    image: "/images/products/greeting-cards-1.jpg",
    purchasable: true,
    price: 1500,
    moq: "1 set",
    leadTime: "Ships in 2–3 working days",
    features: ["10 cards + 10 envelopes", "Blank inside", "Plant-and-grow instruction card included"],
  },
  {
    slug: "seed-balls-jar",
    name: "Seed Balls Jar (20 balls)",
    tagline: "Toss-and-grow seed bombs for giveaways",
    description:
      "A jar of 20 wildflower seed balls — a popular eco giveaway and CSR favourite. Just toss in soil and water.",
    category: "event",
    segments: ["csr-corporate-gifts", "weddings-events"],
    image: "/images/products/seed-balls-1.jpg",
    purchasable: true,
    price: 1000,
    moq: "1 jar",
    leadTime: "Ships in 2–3 working days",
    features: ["20 wildflower seed balls", "Reusable jar", "Custom-label available on bulk"],
  },
  {
    slug: "plantable-bookmarks",
    name: "Plantable Bookmarks (Set of 10)",
    tagline: "Read it, then grow it",
    description:
      "Seed-paper bookmarks that grow into herbs once you're done with them. A low-cost, high-delight giveaway.",
    category: "cards-stationery",
    segments: ["csr-corporate-gifts"],
    image: "/images/products/tags-bookmarks-1.jpg",
    purchasable: true,
    price: 800,
    moq: "1 set",
    leadTime: "Ships in 2–3 working days",
    features: ["10 seed-paper bookmarks", "Basil / mixed herb seeds"],
  },
  {
    slug: "blank-seed-paper-tags",
    name: "Blank Seed Paper Tags (50 pcs)",
    tagline: "Plantable hang tags, ready to brand",
    description:
      "Pre-cut blank seed-paper hang tags with string. Stamp or print your own, or order custom-printed in bulk.",
    category: "tags-inserts",
    segments: ["plantable-brand-materials"],
    image: "/images/products/tags-bookmarks-2.jpg",
    purchasable: true,
    price: 1000,
    moq: "1 pack of 50",
    leadTime: "Ships in 2–3 working days",
    features: ["50 pre-cut tags + string", "Plantable seed paper", "Custom printing available in bulk"],
  },

  // ---------- Custom / bulk → Request a quote ----------
  {
    slug: "custom-shopping-bags",
    name: "Custom Plantable Shopping Bags",
    tagline: "Your retail bag, biodegradable and brandable",
    description:
      "Custom-sized shopping bags in our biodegradable / seed-paper stock, printed with your logo and brand colours. The first offline ad your customer carries home.",
    category: "bags-sleeves",
    segments: ["plantable-brand-materials"],
    image: "/images/products/petal-bags-colorful.jpg",
    purchasable: false,
    moq: "From 300–500 units",
    leadTime: "7–12 working days after approval",
    features: ["Custom size & handle", "Logo + brand-colour printing", "Multiple GSM/thickness options"],
    featured: true,
    seo: {
      keywords: [
        "custom shopping bags Pakistan",
        "biodegradable shopping bags",
        "plantable retail bags Pakistan",
      ],
    },
  },
  {
    slug: "seed-paper-sheets-bulk",
    name: "Seed Paper Sheets — Bulk (A4)",
    tagline: "Plantable stock for your production run",
    description:
      "Bulk A4 plantable seed-paper sheets for your own printing and converting. Choose GSM, seed type and quantity.",
    category: "seed-paper",
    segments: ["seed-paper-stock"],
    image: "/images/products/artistic-sheets-2.jpg",
    purchasable: false,
    moq: "From 300 A4 sheets",
    leadTime: "5–10 working days",
    features: ["GSM/thickness options", "Seed selection (seasonal)", "Largest stock size 15\" × 20\" deckle edge"],
  },
  {
    slug: "plantable-business-cards",
    name: "Plantable Business Cards",
    tagline: "A business card that grows into a plant",
    description:
      "Custom plantable business cards printed with your brand. Most business cards get binned — yours gets planted.",
    category: "cards-stationery",
    segments: ["plantable-brand-materials", "csr-corporate-gifts"],
    image: "/images/products/tags-bookmarks-3.jpg",
    purchasable: false,
    moq: "From 250 cards",
    leadTime: "5–8 working days",
    features: ["Custom print, both sides", "Seed selection", "Optional embossing"],
  },
  {
    slug: "seed-paper-calendars",
    name: "Plantable Calendars",
    tagline: "A desk calendar your clients can plant page by page",
    description:
      "Custom seed-paper calendars for corporate gifting and CSR campaigns — each page plants into herbs or flowers.",
    category: "corporate",
    segments: ["csr-corporate-gifts"],
    image: "/images/products/calendars-1.jpg",
    purchasable: false,
    moq: "From 300–500 units",
    leadTime: "10–15 working days",
    features: ["Custom design & branding", "Desk or wall formats", "Plantable pages"],
    featured: true,
  },
  {
    slug: "plantable-diaries",
    name: "Plantable Diaries & Notebooks",
    tagline: "Seed-paper covers, your branding",
    description:
      "Branded diaries and notebooks with plantable seed-paper covers and inserts — premium corporate gifting.",
    category: "corporate",
    segments: ["csr-corporate-gifts"],
    image: "/images/products/diary-1.jpg",
    purchasable: false,
    moq: "From 100 units",
    leadTime: "10–15 working days",
    features: ["Seed-paper cover", "Custom branding", "Paper-stock options"],
  },
  {
    slug: "branded-sleeves-inserts",
    name: "Branded Sleeves & Inserts",
    tagline: "Thank-you cards, sleeves & inserts that grow",
    description:
      "Custom plantable sleeves, inserts and thank-you cards for cosmetics, wellness and retail brands — match your unboxing to your values.",
    category: "tags-inserts",
    segments: ["plantable-brand-materials"],
    image: "/images/products/plantable-bags-1.jpg",
    purchasable: false,
    moq: "From 300 units",
    leadTime: "7–10 working days",
    features: ["Custom size & print", "Seed-paper or biodegradable stock", "Care-card / instruction printing"],
  },
  {
    slug: "wedding-invitations",
    name: "Plantable Wedding Invitations",
    tagline: "An invitation that grows after the wedding",
    description:
      "Custom plantable invitations and envelopes — guests plant the card and remember your day every time it blooms.",
    category: "event",
    segments: ["weddings-events"],
    image: "/images/products/wedding-cards-1.jpg",
    purchasable: false,
    moq: "From 300–500 sets",
    leadTime: "10–15 working days",
    features: ["Custom design & print", "Matching envelopes & tags", "Seed selection"],
    featured: true,
  },
  {
    slug: "plantable-confetti",
    name: "Plantable Confetti & Giveaways",
    tagline: "Celebrate without the plastic",
    description:
      "Biodegradable seed-paper confetti, favours and giveaways for weddings, launches and events.",
    category: "event",
    segments: ["weddings-events", "csr-corporate-gifts"],
    purchasable: false,
    moq: "From 50 packs",
    leadTime: "5–10 working days",
    features: ["Seed-paper confetti", "Custom favour packaging", "Event branding"],
  },
  {
    slug: "corporate-gift-boxes",
    name: "Corporate Gift Boxes",
    tagline: "Plantable gift sets that signal real sustainability",
    description:
      "Curated plantable corporate gift boxes — cards, calendars, seed balls and packaging branded for your campaign.",
    category: "corporate",
    segments: ["csr-corporate-gifts"],
    image: "/images/products/artistic-sheets-1.jpg",
    purchasable: false,
    moq: "From 50 boxes",
    leadTime: "10–15 working days",
    features: ["Custom box & contents", "Logo + campaign message", "Bulk delivery planning"],
  },
  {
    slug: "hang-tags-price-tags",
    name: "Custom Hang Tags & Price Tags",
    tagline: "Plantable tags printed with your brand",
    description:
      "Custom-printed seed-paper hang tags and price tags for fashion and retail — durable enough to hang, plantable when removed.",
    category: "tags-inserts",
    segments: ["plantable-brand-materials"],
    image: "/images/products/price-tags-1.jpg",
    purchasable: false,
    moq: "From 500 tags",
    leadTime: "7–10 working days",
    features: ["Custom shape & size", "Logo printing", "String/eyelet options"],
  },
  {
    slug: "seed-paper-coasters",
    name: "Plantable Seed Paper Coasters",
    tagline: "Coasters that grow into herbs when you're done with them",
    description:
      "Custom-printed circular or square seed-paper coasters — a conversation piece at every event table. Use them, then plant them.",
    category: "event",
    segments: ["csr-corporate-gifts", "weddings-events"],
    image: "/images/products/coasters-1.jpg",
    purchasable: false,
    moq: "From 100 units",
    leadTime: "7–10 working days",
    features: [
      "Custom print (logo, event date, message)",
      "Circle or square format",
      "Wildflower or herb seed selection",
    ],
    seo: {
      seoTitle: "Plantable Seed Paper Coasters — Custom Branded Pakistan",
      metaDescription:
        "Custom seed-paper coasters that grow into plants after use. Ideal for corporate events, weddings and CSR gifting. Made in Pakistan.",
      keywords: ["plantable coasters Pakistan", "seed paper coasters", "eco coasters corporate"],
    },
  },
  {
    slug: "plantable-pennants",
    name: "Plantable Pennants",
    tagline: "Decorative pennants you hang, then plant",
    description:
      "Seed-paper pennants in custom shapes and sizes — great for product launches, events and store décor. After the event, guests take them home and plant them.",
    category: "event",
    segments: ["weddings-events", "plantable-brand-materials"],
    image: "/images/products/pennants-1.jpg",
    purchasable: false,
    moq: "From 50 units",
    leadTime: "7–10 working days",
    features: [
      "Custom shape, size and print",
      "String/twine included",
      "Mixed herb or wildflower seeds",
    ],
    seo: {
      seoTitle: "Plantable Pennants — Seed Paper Event Decor Pakistan",
      metaDescription:
        "Custom seed-paper pennants for events, launches and brand décor. Guests take them home and plant them. Made in Pakistan.",
      keywords: ["plantable pennants Pakistan", "seed paper pennants", "eco event decor Pakistan"],
    },
  },
];
