import type { Product } from "./types";

// NOTE: prices are placeholders for the productized SKUs (confirm before launch).
// Purchasable = fixed-price standard items (checkout). Everything custom/bulk
// routes to Request-a-Quote, per the strategy.

export const products: Product[] = [
  // ---------- Purchasable standard SKUs ----------
  {
    slug: "sample-kit",
    name: "Plantable Sample Kit",
    tagline: "Samples + a 15-min consult before you commit to bulk",
    description:
      "The smartest first step. Seed-paper swatches, printing and embossing examples, and card, tag and calendar format samples arrive in your hands, along with a 15-minute consultation. The kit price is adjusted against your first bulk order.",
    category: "seed-paper",
    segments: ["csr-corporate-gifts", "plantable-brand-materials", "weddings-events"],
    purchasable: true,
    price: 3500,
    leadTime: "Ships in 2–3 working days",
    features: [
      "Seed-paper + biodegradable stock swatches",
      "Print, embossing & finishing examples",
      "Card, tag & calendar format samples",
      "15-minute consultation",
      "Kit price adjusted against your bulk order",
    ],
    image: "/images/products/product-spread-grass.jpg",
    featured: true,
    seo: {
      seoTitle: "Plantable Seed Paper Sample Kit — Boxit Pakistan",
      metaDescription:
        "Order Boxit's plantable seed paper sample kit: seed-paper swatches, print & finishing examples, and a consult. Cost adjusted against your bulk order.",
      keywords: [
        "seed paper sample kit",
        "plantable paper samples Pakistan",
        "seed paper test pack",
      ],
    },
  },
  {
    slug: "seed-paper-a5-pack",
    name: "Seed Paper A5 Pack (25 sheets)",
    tagline: "Plantable A5 sheets for cards, notes & DIY",
    description:
      "Tree-free, seed-embedded A5 sheets you can print, write or craft on, then plant. Grows into herbs and wildflowers. Great for testing before a bulk run.",
    category: "seed-paper",
    segments: ["seed-paper-stock", "weddings-events"],
    image: "/images/products/seed-paper-a5-printed.jpg",
    gallery: [
      "/images/products/seed-paper-a5-printed.jpg",
      "/images/products/seed-paper-a5-printed-cards.jpg",
    ],
    purchasable: true,
    price: 1200,
    moq: "1 pack",
    leadTime: "Ships in 2–3 working days",
    features: ["25 × A5 seed paper sheets", "Mixed herb / wildflower seeds", "Tree-free, 100% biodegradable"],
  },
  {
    slug: "plantable-greeting-cards-set",
    name: "Plantable Greeting Cards (Set of 10)",
    tagline: "Cards that grow into flowers",
    description:
      "Ten blank plantable greeting cards with envelopes. Write your message, gift it, then plant the card. Ideal for personal gifting and small businesses.",
    category: "cards-stationery",
    segments: ["csr-corporate-gifts", "weddings-events"],
    image: "/images/products/greeting-cards-spread.png",
    gallery: [
      "/images/products/greeting-cards-spread.png",
      "/images/products/greeting-cards-1.jpg",
    ],
    purchasable: true,
    price: 1500,
    moq: "1 set",
    leadTime: "Ships in 2–3 working days",
    features: ["10 cards + 10 envelopes", "Blank inside", "Planting guide included"],
  },
  {
    slug: "custom-seed-balls-bulk",
    name: "Custom Seed Balls (Bulk)",
    tagline: "Wildflower seed bombs for large giveaways",
    description:
      "Bulk wildflower seed balls for CSR drives, events and corporate giveaways. Recipients press one into soil, water it, and leave the rest to the weather. Add custom-printed pouches to brand them.",
    category: "seed-balls",
    segments: ["csr-corporate-gifts", "weddings-events"],
    image: "/images/products/seed-balls-bkk.jpg",
    purchasable: false,
    moq: "From 500 balls",
    leadTime: "5–10 working days",
    features: ["Wildflower seed mix", "Bulk packed", "Optional branded pouches"],
  },
  {
    slug: "plantable-bookmarks",
    name: "Plantable Bookmarks (Set of 10)",
    tagline: "Read it, then grow it",
    description:
      "Seed-paper bookmarks that grow into herbs once the book is finished. Light, flat and cheap to post, which makes them an easy giveaway for bookshops, libraries and reading campaigns.",
    category: "cards-stationery",
    segments: ["csr-corporate-gifts"],
    image: "/images/products/tags-bookmarks-1.jpg",
    purchasable: true,
    price: 800,
    moq: "1 set",
    leadTime: "Ships in 2–3 working days",
    features: ["10 seed-paper bookmarks", "Basil / mixed herb seeds"],
  },
  {
    slug: "blank-seed-paper-tags",
    name: "Blank Seed Paper Tags (50 pcs)",
    tagline: "Plantable hang tags, ready to brand",
    description:
      "Pre-cut blank seed-paper hang tags with string. Stamp or print your own, or order custom-printed in bulk.",
    category: "tags-inserts",
    segments: ["plantable-brand-materials"],
    image: "/images/products/tags-bookmarks-2.jpg",
    purchasable: true,
    price: 1000,
    moq: "1 pack of 50",
    leadTime: "Ships in 2–3 working days",
    features: ["50 pre-cut tags + string", "Plantable seed paper", "Custom printing available in bulk"],
  },

  // ---------- Custom / bulk → Request a quote ----------
  {
    slug: "custom-shopping-bags",
    name: "Custom Plantable Shopping Bags",
    tagline: "Your retail bag, biodegradable and brandable",
    description:
      "Shopping bags cut to your own size in biodegradable or seed-paper stock, printed with your logo and brand colors. Built to carry real retail weight: we match GSM and handle type to what your customers actually buy.",
    category: "bags-sleeves",
    segments: ["plantable-brand-materials"],
    image: "/images/clients/client-metro-kit-flatlay.jpg",
    purchasable: false,
    moq: "From 200 bags",
    leadTime: "7–12 working days after approval",
    features: ["Sized to your shelf and basket", "Logo + brand-color printing", "Multiple GSM/thickness options"],
    featured: true,
    seo: {
      keywords: [
        "custom shopping bags Pakistan",
        "biodegradable shopping bags",
        "plantable retail bags Pakistan",
      ],
    },
  },
  {
    slug: "seed-paper-petal-bags",
    name: "Seed Paper & Petal Bags",
    tagline: "Petal-embedded stock in strong colors",
    description:
      "Gift bags made from seed paper with real petals pressed into the sheet, finished with contrast rope handles. This is the most decorative bag we make: the color and petal flecks are in the paper itself, not printed on. The whole bag plants into flowers.",
    category: "bags-sleeves",
    segments: ["plantable-brand-materials", "weddings-events"],
    image: "/images/products/petal-bags-colorful.jpg",
    purchasable: false,
    moq: "From 200 bags",
    leadTime: "7–12 working days after approval",
    features: ["Real petals embedded in the sheet", "Contrast rope handles", "Custom size & paper colors"],
  },
  {
    slug: "plantable-gift-bags",
    name: "Plantable Gift Bags",
    tagline: "The small format, for one gift at a time",
    description:
      "Our smallest bag size, built to hold a single item: a candle, a jar, a favor box, a piece of jewelry. Printed with your artwork and fitted with rope handles. Because the format is small, the print sits large on the panel, so short messages and single logos read well from across a room.",
    category: "bags-sleeves",
    segments: ["plantable-brand-materials", "csr-corporate-gifts"],
    image: "/images/products/bag-sunshine-blue.jpg",
    purchasable: false,
    moq: "From 200 bags",
    leadTime: "7–12 working days after approval",
    features: ["Small single-gift format", "Full-panel artwork", "Rope handles"],
  },
  {
    slug: "plantable-paper-bags",
    name: "Plantable Paper Bags",
    tagline: "The everyday counter bag, in natural kraft",
    description:
      "Our standard over-the-counter bag in a natural, unbleached kraft look. Your logo prints on the front and the planting guide goes on the reverse, so the customer works out what to do with it without anyone at the counter having to explain. The plain paper color keeps single-color print costs down on long runs.",
    category: "bags-sleeves",
    segments: ["plantable-brand-materials", "csr-corporate-gifts"],
    image: "/images/products/bag-unwomen.jpg",
    purchasable: false,
    moq: "From 200 bags",
    leadTime: "7–12 working days after approval",
    features: ["Natural unbleached kraft look", "Logo front, planting guide back", "Economical on single-color runs"],
  },
  {
    slug: "event-campaign-bags",
    name: "Event & Campaign Bags",
    tagline: "Plantable bags for launches, awareness days and CSR events",
    description:
      "Bags printed for one occasion: a launch, an awareness day, a conference. The artwork usually carries a date, a theme and a hashtag rather than a permanent logo, which means the run is fixed and the deadline is real. Send us the campaign key visual and we work backwards from your event date.",
    category: "bags-sleeves",
    segments: ["csr-corporate-gifts", "plantable-brand-materials"],
    image: "/images/products/bag-world-env.jpg",
    purchasable: false,
    moq: "From 200 bags",
    leadTime: "7–12 working days after approval",
    features: ["Dated campaign artwork", "Fixed run, scheduled to your event date", "Rope handles"],
  },
  {
    slug: "branded-kraft-bags",
    name: "Branded Kraft Shopping Bags",
    tagline: "Landscape kraft retail bags printed with your brand",
    description:
      "A wide, landscape-shaped kraft bag for things that do not fit a tall bag: folded garments, flat boxes, framed pieces, hampers. The broad front panel also gives a logo room to sit horizontally the way most brand marks are actually drawn.",
    category: "bags-sleeves",
    segments: ["plantable-brand-materials", "csr-corporate-gifts"],
    image: "/images/products/bag-wed.jpg",
    purchasable: false,
    moq: "From 200 bags",
    leadTime: "7–12 working days after approval",
    features: ["Wide landscape format", "Suits flat and folded goods", "Horizontal logo lockups print well"],
  },
  {
    slug: "plantable-bag-range",
    name: "Plantable Bag Range",
    tagline: "Start here if none of the standard formats fit",
    description:
      "Every bag on this page starts from the same seed-paper stock, so if your size, handle or finish is not listed we can still make it. Send us the dimensions you need, your artwork and a quantity, and we will quote the format rather than pushing you into the nearest standard one. This is also the right entry to ask about mixed runs across several sizes.",
    category: "bags-sleeves",
    segments: ["plantable-brand-materials", "csr-corporate-gifts", "weddings-events"],
    image: "/images/products/bag-range.jpg",
    purchasable: false,
    moq: "From 200 bags",
    leadTime: "7–12 working days after approval",
    features: ["Non-standard sizes made to spec", "Mixed-size runs possible", "Quoted from your dimensions"],
  },
  {
    slug: "corporate-plantable-bags",
    name: "Corporate & Institutional Bags",
    tagline: "Plantable bags for corporate, NGO and institutional campaigns",
    description:
      "Bags produced to a brand manual. We work from your supplied logo files and color references, and hold the artwork through your internal approval rounds. Built for corporates, NGOs and public-sector programs where the print has to pass a compliance check before it goes to press.",
    category: "bags-sleeves",
    segments: ["csr-corporate-gifts", "plantable-brand-materials"],
    image: "/images/products/secp-unwomen-bag.jpg",
    purchasable: false,
    moq: "From 200 bags",
    leadTime: "7–12 working days after approval",
    features: ["Printed to your brand manual", "Artwork proofs through your approval rounds", "Suited to compliance-checked print"],
  },
  {
    slug: "plantable-giveaway-bags",
    name: "Plantable Giveaway Bags",
    tagline: "Light twine-handle bags for delegate kits",
    description:
      "A lighter bag with twine handles rather than rope, made for handing out in volume at conference desks and CSR drives. It holds a notebook, a pen and a leaflet, and carries your message and the planting guide printed together on one panel.",
    category: "bags-sleeves",
    segments: ["csr-corporate-gifts", "plantable-brand-materials"],
    image: "/images/products/gar-bag-1.jpg",
    gallery: [
      "/images/products/gar-bag-1.jpg",
      "/images/products/gar-bag-2.jpg",
    ],
    purchasable: false,
    moq: "From 200 bags",
    leadTime: "7–12 working days after approval",
    features: ["Twine handles, lighter build", "Sized for a notebook and leaflet", "Planting guide printed on the bag"],
  },
  {
    slug: "seed-paper-sheets-bulk",
    name: "Seed Paper Sheets — Bulk (A4)",
    tagline: "Plantable stock for your production run",
    description:
      "Bulk A4 plantable seed paper supplied as flat stock for your own printing and converting. Choose GSM, seed type and quantity. Our largest sheet size is 15\" × 20\" with a deckle edge if you need to cut your own formats.",
    category: "seed-paper",
    segments: ["seed-paper-stock"],
    image: "/images/products/seed-paper-sheets-colored-fan.jpg",
    gallery: [
      "/images/products/seed-paper-sheets-colored-fan.jpg",
      "/images/products/seed-paper-sheets-stack.jpg",
    ],
    purchasable: false,
    moq: "From 300 A4 sheets",
    leadTime: "5–10 working days",
    features: ["GSM/thickness options", "Seed selection (seasonal)", "Largest stock size 15\" × 20\" deckle edge"],
  },
  {
    slug: "plantable-business-cards",
    name: "Plantable Business Cards",
    tagline: "A business card that grows into a plant",
    description:
      "Custom business cards printed on seed paper, both sides, with optional embossing. The stock is thicker and more textured than a standard card, so it registers in the hand before anyone reads it. Tell us your seed preference and we match it to the season you are printing for.",
    category: "cards-stationery",
    segments: ["plantable-brand-materials", "csr-corporate-gifts"],
    image: "/images/products/agha-steel-invite.png",
    gallery: [
      "/images/products/agha-steel-invite.png",
      "/images/products/ejad-tech-summit-a.png",
      "/images/products/ejad-tech-summit-b.png",
    ],
    purchasable: false,
    moq: "From 1,200 cards",
    leadTime: "5–8 working days",
    features: ["Custom print, both sides", "Seed selection", "Optional embossing"],
  },
  {
    slug: "seed-paper-calendars",
    name: "Plantable Calendars",
    tagline: "A desk calendar your clients can plant page by page",
    description:
      "Custom seed-paper calendars for corporate gifting and CSR campaigns. Each page plants into herbs or flowers, so the gift keeps working for twelve months and then does one more thing.",
    category: "corporate",
    segments: ["csr-corporate-gifts"],
    image: "/images/products/calendars-fan-easel.png",
    gallery: [
      "/images/products/calendars-fan-easel.png",
      "/images/products/calendars-1.jpg",
    ],
    purchasable: false,
    moq: "From 200 calendars",
    leadTime: "10–15 working days",
    features: ["Custom design & branding", "Desk or wall formats", "Plantable pages"],
    featured: true,
  },
  {
    slug: "plantable-desk-calendar",
    name: "Plantable Desk Calendar",
    tagline: "A tear-off desk calendar on a wooden easel",
    description:
      "A standing monthly calendar on a mini wooden easel. Each printed page tears off cleanly at the end of the month and plants into herbs or flowers, so your branding sits on the desk all year and the easel stays behind after the pages are gone.",
    category: "corporate",
    segments: ["csr-corporate-gifts"],
    image: "/images/products/desk-calendar-easel.png",
    purchasable: false,
    moq: "From 200 calendars",
    leadTime: "10–15 working days",
    features: ["Monthly tear-off pages", "Mini wooden easel stand", "Custom photo & branding"],
  },
  {
    slug: "seed-paper-desk-calendar",
    name: "Seed Paper Desk Calendar",
    tagline: "Mini easel calendar on textured seed-paper stock",
    description:
      "A compact desk calendar on a mini easel, printed on our textured plantable stock with different artwork for each month. Smaller than the tear-off version and easier to post, which makes it a practical choice for gifting lists spread across cities.",
    category: "corporate",
    segments: ["csr-corporate-gifts"],
    image: "/images/products/seed-paper-calendars-easel.png",
    purchasable: false,
    moq: "From 200 calendars",
    leadTime: "10–15 working days",
    features: ["Seed-paper plantable pages", "Mini easel stand", "Custom monthly artwork"],
  },
  {
    slug: "plantable-diaries",
    name: "Plantable Diaries (A5)",
    tagline: "A5 diaries with plantable outer seed-paper covers",
    description:
      "Branded A5 diaries bound with a plantable seed-paper outer cover. The inner pages are ordinary writing stock, so the diary works as a diary all year, and the cover goes into a pot once it is finished.",
    category: "corporate",
    segments: ["csr-corporate-gifts"],
    image: "/images/products/diary-1.jpg",
    purchasable: false,
    moq: "From 300 units",
    leadTime: "10–15 working days",
    features: ["A5 format", "Outer seed-paper cover", "Custom branding & paper-stock options"],
  },
  {
    slug: "plantable-notebooks",
    name: "Plantable Notebooks",
    tagline: "Notebooks with plantable outer seed-paper covers",
    description:
      "Custom notebooks with plantable seed-paper outer covers and your branding. Lighter and lower in cost than the A5 diary, which makes them the sensible pick when the gifting list runs long.",
    category: "corporate",
    segments: ["csr-corporate-gifts"],
    image: "/images/products/plantable-notebook-eco-pen.jpg",
    gallery: [
      "/images/products/plantable-notebook-eco-pen.jpg",
      "/images/products/lumovy-notebook.jpg",
      "/images/products/jazzworld-notebook.jpg",
    ],
    purchasable: false,
    moq: "From 300 units",
    leadTime: "10–15 working days",
    features: ["Outer seed-paper cover", "Custom branding", "Paper-stock options"],
  },
  {
    slug: "branded-sleeves-inserts",
    name: "Branded Sleeves & Inserts",
    tagline: "Thank-you cards, sleeves & inserts that grow",
    description:
      "Custom plantable sleeves, inserts and thank-you cards for cosmetics, wellness and retail brands. These are the pieces a customer handles first when the parcel opens, so we cut them to sit correctly inside your existing box.",
    category: "tags-inserts",
    segments: ["plantable-brand-materials"],
    image: "/images/products/knisa-thankyou-a.png",
    gallery: [
      "/images/products/knisa-thankyou-a.png",
      "/images/products/knisa-thankyou-b.png",
      "/images/products/knisa-thankyou-c.png",
      "/images/products/knisa-thankyou-d.png",
    ],
    purchasable: false,
    moq: "From 500 units",
    leadTime: "7–10 working days",
    features: ["Cut to fit your existing box", "Seed-paper or biodegradable stock", "Care-card and planting-guide printing"],
  },
  {
    slug: "wedding-invitations",
    name: "Plantable Wedding Invitations",
    tagline: "An invitation that grows after the wedding",
    description:
      "Custom plantable invitations with matching envelopes and tags. Guests plant the card after the day, and it flowers in the season that follows. Seed choice is yours, and we will tell you what suits the month you are printing for.",
    category: "event",
    segments: ["weddings-events"],
    image: "/images/products/walima-invites.png",
    purchasable: false,
    moq: "From 300–500 sets",
    leadTime: "10–15 working days",
    features: ["Custom design & print", "Matching envelopes & tags", "Seed selection"],
    featured: true,
  },
  {
    slug: "plantable-invitation-cards",
    name: "Plantable Invitation Cards",
    tagline: "Seed-paper cards for weddings & celebrations",
    description:
      "Custom invitation and event cards printed on seed paper with your design and foliage motifs. A simpler, single-card format than the full wedding suite, at a lower minimum, for mehndis, milads, birthdays and smaller functions.",
    category: "event",
    segments: ["weddings-events"],
    image: "/images/products/wedding-cards-1.jpg",
    purchasable: false,
    moq: "From 300 cards",
    leadTime: "10–15 working days",
    features: ["Custom design & print", "Matching envelopes", "Seed selection"],
  },
  {
    slug: "plantable-confetti",
    name: "Plantable Confetti & Giveaways",
    tagline: "Celebrate without the plastic",
    description:
      "Seed-paper confetti, favors and small giveaways for weddings, launches and events. Punched from the same plantable stock as our cards, in the shapes and colors you choose, with the lowest minimum in our event range.",
    category: "event",
    segments: ["weddings-events", "csr-corporate-gifts"],
    image: "/images/products/confetti-giveaways-cards.jpg",
    purchasable: false,
    moq: "From 50 packs",
    leadTime: "5–10 working days",
    features: ["Punched in custom shapes", "Custom favor packaging", "Event branding"],
  },
  {
    slug: "hang-tags-price-tags",
    name: "Custom Hang Tags & Price Tags",
    tagline: "Plantable tags printed with your brand",
    description:
      "Custom-printed seed-paper hang tags and price tags for fashion and retail. Stiff enough to take an eyelet and survive a rail without curling, and plantable once the customer cuts them off.",
    category: "tags-inserts",
    segments: ["plantable-brand-materials"],
    image: "/images/products/tags-bookmarks-1.jpg",
    purchasable: false,
    moq: "From 500 tags",
    leadTime: "7–10 working days",
    features: ["Custom shape & size", "Logo printing", "String/eyelet options"],
  },
  {
    slug: "client-branded-hang-tags",
    name: "Branded Hang Tags — Client Work",
    tagline: "Seed-paper hang tags we have printed for brands",
    description:
      "Work we have already run for retail and lifestyle brands: seed-paper tags with logos, planting guides and twine, in the shapes those brands specified. Useful if you want to see how a real logo and a real tag shape come out on this stock before committing your own artwork.",
    category: "tags-inserts",
    segments: ["plantable-brand-materials"],
    image: "/images/products/hang-tags-branded-1.jpg",
    gallery: [
      "/images/products/hang-tags-branded-1.jpg",
      "/images/products/hang-tags-branded-2.jpg",
      "/images/products/hang-tags-branded-3.jpg",
    ],
    purchasable: false,
    moq: "From 500 tags",
    leadTime: "7–10 working days",
    features: ["Custom shape & print", "Twine / eyelet options", "Planting guide printed on the tag"],
  },
  {
    slug: "plantable-event-invitations",
    name: "Plantable Event Invitations",
    tagline: "Seed-paper invites with matching plantable envelopes",
    description:
      "Invitation cards with seed-paper envelopes to match, for weddings, valimas and events. Card and envelope are both plantable, so nothing in the set is left over. Your artwork goes on the card and the planting guide on the envelope.",
    category: "event",
    segments: ["plantable-brand-materials", "weddings-events"],
    image: "/images/products/branded-insert-invite.jpg",
    purchasable: false,
    moq: "From 300 invites",
    leadTime: "10–15 working days",
    features: ["Custom artwork & print", "Matching seed-paper envelope", "Planting guide printed on the envelope"],
  },
  {
    slug: "corporate-plantable-cards",
    name: "Corporate Plantable Cards",
    tagline: "Branded greeting, event & CSR cards that grow",
    description:
      "Greeting cards, event invites and CSR message cards printed on seed paper with your branding, in folded or flat formats. One artwork can run across the whole set, so Eid, year-end and campaign cards stay consistent across departments.",
    category: "cards-stationery",
    segments: ["plantable-brand-materials", "csr-corporate-gifts"],
    image: "/images/products/branded-inserts-corporate.jpg",
    purchasable: false,
    moq: "From 300 cards",
    leadTime: "10–15 working days",
    features: ["Custom branding & print", "Folded or flat formats", "Planting guide printed inside"],
  },
  {
    slug: "seed-paper-coasters",
    name: "Plantable Seed Paper Coasters",
    tagline: "Coasters that grow into herbs when you're done with them",
    description:
      "Custom-printed seed-paper coasters in circle or square format. Pressed thick enough to sit flat under a glass through an evening, printed with your logo, event date or message, and planted afterwards.",
    category: "event",
    segments: ["csr-corporate-gifts", "weddings-events"],
    image: "/images/products/coasters-1.jpg",
    purchasable: false,
    moq: "From 500 coasters",
    leadTime: "7–10 working days",
    features: [
      "Custom print (logo, event date, message)",
      "Circle or square format",
      "Wildflower or herb seed selection",
    ],
    seo: {
      seoTitle: "Plantable Seed Paper Coasters — Custom Branded Pakistan",
      metaDescription:
        "Custom seed-paper coasters that grow into plants after use. Ideal for corporate events, weddings and CSR gifting. Made in Pakistan.",
      keywords: ["plantable coasters Pakistan", "seed paper coasters", "eco coasters corporate"],
    },
  },
  {
    slug: "plantable-pennants",
    name: "Plantable Pennants",
    tagline: "Decorative pennants you hang, then plant",
    description:
      "Seed-paper pennants in custom shapes and sizes, strung on twine for product launches, events and store décor. Hang them across a stall or a shopfront, then let guests take one home and plant it.",
    category: "event",
    segments: ["weddings-events", "plantable-brand-materials"],
    image: "/images/products/pennants-1.jpg",
    purchasable: false,
    moq: "From 500 pennants",
    leadTime: "7–10 working days",
    features: [
      "Custom shape, size and print",
      "String/twine included",
      "Mixed herb or wildflower seeds",
    ],
    seo: {
      seoTitle: "Plantable Pennants — Seed Paper Event Decor Pakistan",
      metaDescription:
        "Custom seed-paper pennants for events, launches and brand décor. Guests take them home and plant them. Made in Pakistan.",
      keywords: ["plantable pennants Pakistan", "seed paper pennants", "eco event decor Pakistan"],
    },
  },

  // ---------- Added to cover every item in the instant estimator ----------
  // MOQ + lead time mirror src/content/estimator.ts (the pricing-sheet source).

  // Seed Paper & Sheets
  {
    slug: "deckle-edge-seed-paper",
    name: "Deckle Edge Seed Paper",
    tagline: "Hand-torn plantable sheets with a raw edge",
    description:
      "Seed-paper sheets finished with a natural, hand-torn border rather than a guillotine cut. Every sheet's edge is slightly different, which is the point: it reads as handmade on invitations, certificates and high-end stationery. Plants into herbs and wildflowers.",
    category: "seed-paper",
    segments: ["seed-paper-stock", "weddings-events"],
    image: "/images/products/seed-paper-sheets-stack.jpg",
    purchasable: false,
    moq: "From 300 sheets",
    leadTime: "7–10 working days",
    features: ["Natural deckle (torn) edge", "Seed selection (seasonal)", "Also available without seeds"],
  },
  {
    slug: "neem-leaf-paper",
    name: "Neem Leaf Paper",
    tagline: "Handmade sheets with real embedded neem leaves",
    description:
      "Tree-free handmade paper with real pressed neem leaves suspended inside the sheet. The leaves catch the light when the sheet is held up, which suits invitations, menus and covers. No two sheets carry the same leaf pattern.",
    category: "seed-paper",
    segments: ["seed-paper-stock", "weddings-events"],
    image: "/images/products/deckle-edge-neem-1.jpg",
    gallery: [
      "/images/products/deckle-edge-neem-1.jpg",
      "/images/products/deckle-edge-neem-2.jpg",
    ],
    purchasable: false,
    moq: "From 300 sheets",
    leadTime: "7–10 working days",
    features: ["Real embedded neem leaves", "Natural deckle (torn) edge", "Tree-free & biodegradable"],
  },
  {
    slug: "deckle-edge-paper",
    name: "Deckle Edge Paper (No Seeds)",
    tagline: "Tree-free deckle-edge stock, without embedded seeds",
    description:
      "The same hand-torn deckle edge in our tree-free, biodegradable paper, without embedded seeds. Choose this when you want the handmade look and the tree-free stock but the piece is not meant to be planted. It costs less than seed paper.",
    category: "seed-paper",
    segments: ["seed-paper-stock", "plantable-brand-materials"],
    image: "/images/products/deckle-edge-no-seeds-blank.jpg",
    purchasable: false,
    moq: "From 300 sheets",
    leadTime: "7–10 working days",
    features: ["Natural deckle (torn) edge", "Tree-free & biodegradable", "No seeds, lower cost"],
  },
  {
    slug: "cotton-paper",
    name: "Cotton Paper",
    tagline: "Soft, durable tree-free cotton-rag stock",
    description:
      "Premium 100% cotton-rag paper: tree-free, biodegradable and soft enough to take a deep letterpress bite. Suits certificates, letterpress work and foil. It carries the lowest minimum in our sheet range, so short runs are workable.",
    category: "seed-paper",
    segments: ["seed-paper-stock", "plantable-brand-materials"],
    image: "/images/products/cotton-paper-rag-trio.png",
    purchasable: false,
    moq: "From 100 sheets",
    leadTime: "7–10 working days",
    features: ["100% cotton-rag stock", "Tree-free & biodegradable", "Takes letterpress & foil well"],
  },

  // Cards & Stationery
  {
    slug: "plantable-envelopes",
    name: "Plantable Envelopes",
    tagline: "Flap or v-shape envelopes that grow when planted",
    description:
      "Custom seed-paper envelopes in flap or v-shape formats, cut to match your invitations, cards and mailers. Order them alongside the card and the whole set arrives plantable, in one paper color, from one production run.",
    category: "cards-stationery",
    segments: ["weddings-events", "plantable-brand-materials"],
    image: "/images/products/plantable-envelopes-blue-1.jpg",
    gallery: [
      "/images/products/plantable-envelopes-blue-1.jpg",
      "/images/products/plantable-envelopes-blue-2.jpg",
      "/images/products/plantable-envelopes-blue-3.jpg",
    ],
    purchasable: false,
    moq: "From 300 envelopes",
    leadTime: "7–10 working days",
    features: ["Flap or v-shape format", "Custom print & size", "Seed selection (seasonal)"],
  },
  {
    slug: "plantable-brochures",
    name: "Plantable Brochures",
    tagline: "Marketing brochures that plant into flowers",
    description:
      "Seed-paper brochures and flyers printed with your campaign, in the fold of your choice. At an expo or a launch, the handout does not have to compete for shelf space at home: the visitor reads it, then plants it. Herb or wildflower seeds.",
    category: "cards-stationery",
    segments: ["plantable-brand-materials", "csr-corporate-gifts"],
    image: "/images/products/greeting-cards-1.jpg",
    purchasable: false,
    moq: "From 500 brochures",
    leadTime: "7–10 working days",
    features: ["Custom fold & print", "Seed-paper stock", "Herb or wildflower seeds"],
  },
  {
    slug: "plantable-letterheads",
    name: "Plantable Letterheads",
    tagline: "Branded letterheads on seed paper",
    description:
      "Custom-printed seed-paper letterheads for correspondence that is meant to be kept and noticed: award letters, appointment letters, thank-you notes to partners. The recipient can plant the page once it has served its purpose. Matching envelopes available.",
    category: "cards-stationery",
    segments: ["plantable-brand-materials", "csr-corporate-gifts"],
    image: "/images/products/letterhead-usaid-linen.png",
    purchasable: false,
    moq: "From 500 sheets",
    leadTime: "7–10 working days",
    features: ["Custom brand printing", "Seed-paper or biodegradable stock", "Matching envelopes available"],
  },
  {
    slug: "plantable-ball-points",
    name: "Plantable Ball Points",
    tagline: "Seeded pens that grow after their last drop of ink",
    description:
      "Ball-point pens with a biodegradable barrel and a seed capsule in the end cap. Your logo prints along the barrel. When the ink runs out the pen goes into soil rather than a drawer, and the capsule grows herbs or flowers.",
    category: "cards-stationery",
    segments: ["csr-corporate-gifts", "plantable-brand-materials"],
    image: "/images/products/ballpoint-kraft-a.png",
    gallery: [
      "/images/products/ballpoint-kraft-a.png",
      "/images/products/ballpoint-kraft-b.png",
      "/images/products/ballpoint-newspaper-wall.png",
      "/images/products/ballpoint-box.png",
    ],
    purchasable: false,
    moq: "From 300 ball points",
    leadTime: "7–10 working days",
    features: ["Seed capsule end-cap", "Custom logo printing", "Biodegradable barrel"],
  },
  {
    slug: "plantable-pencils",
    name: "Plantable Pencils",
    tagline: "Seeded pencils you plant when they're too short to use",
    description:
      "Wooden pencils with a seed capsule on the end and your logo engraved into the barrel. Write with them, then plant the stub to grow herbs or flowers. Popular for school programs, CSR drives and event kits.",
    category: "cards-stationery",
    segments: ["csr-corporate-gifts", "plantable-brand-materials"],
    image: "/images/products/newspaper-pencils-wall.png",
    gallery: [
      "/images/products/newspaper-pencils-wall.png",
      "/images/products/newspaper-pencils-bagged.png",
      "/images/products/newspaper-pencils-closeup.png",
    ],
    purchasable: false,
    moq: "From 300 pencils",
    leadTime: "7–10 working days",
    features: ["Seed capsule on the end", "Custom logo engraving", "Herb / flower seed options"],
  },

  // Weddings & Events
  {
    slug: "seed-ball-pouches",
    name: "Pouches for Seed Balls",
    tagline: "Branded pouches to package your seed balls",
    description:
      "Custom-printed pouches cut to hold our wildflower seed balls, so a loose ball becomes something you can hand over and post. Pair them with a bulk seed-ball run. Print your logo and the planting guide on the face.",
    category: "seed-balls",
    segments: ["csr-corporate-gifts", "weddings-events"],
    image: "/images/products/seed-balls-1.jpg",
    purchasable: false,
    moq: "From 250 pouches",
    leadTime: "5–10 working days",
    features: ["Sized for seed balls", "Custom print & branding", "Seed-paper or biodegradable stock"],
  },
  {
    slug: "plantable-event-stationery",
    name: "Plantable Events Cards",
    tagline: "Menus, place cards & signage that guests can plant",
    description:
      "Menus, place cards, table numbers and small signage, all printed on seed paper for one event. Ordering them together keeps the paper color, seed type and typography consistent across every table, and guests can plant the pieces afterwards.",
    category: "event",
    segments: ["weddings-events", "csr-corporate-gifts"],
    image: "/images/products/event-stationery-cards.jpg",
    purchasable: false,
    moq: "From 500 items",
    leadTime: "7–10 working days",
    features: ["Menus, place cards, signage", "Custom design & print", "Herb / wildflower seeds"],
  },

  // Calendars, Diaries & Corporate
  {
    slug: "corporate-souvenir-set-economical",
    name: "Corporate Souvenir Set — Economical",
    tagline: "An entry-level plantable gift set for large runs",
    description:
      "A budget-friendly souvenir set built from our lighter items: seed-paper stationery and small giveaways, branded for your campaign. Priced for the runs where every recipient on a long list gets the same thing.",
    category: "corporate",
    segments: ["csr-corporate-gifts"],
    image: "/images/products/product-spread-grass.jpg",
    purchasable: false,
    moq: "From 200 sets",
    leadTime: "10–15 working days",
    features: ["Lighter plantable items", "Campaign branding", "Bulk delivery planning"],
  },
  {
    slug: "corporate-souvenir-set-executive",
    name: "Corporate Souvenir Set — Executive",
    tagline: "A mid-tier plantable gift set for client gifting",
    description:
      "A step up from Economical: heavier seed-paper stationery, more pieces per set, and a branded box to present them in. Suits client and partner gifting, where the set is handed over in person.",
    category: "corporate",
    segments: ["csr-corporate-gifts"],
    image: "/images/products/sample-kit-spread.jpg",
    purchasable: false,
    moq: "From 100 sets",
    leadTime: "10–15 working days",
    features: ["Heavier stock, more pieces per set", "Branded gift box", "Campaign messaging"],
  },
  {
    slug: "corporate-souvenir-set-premium",
    name: "Corporate Souvenir Set — Premium",
    tagline: "Our top-tier plantable souvenir set",
    description:
      "Our top set: the A5 seed-paper diary, a desk calendar and our best gifting pieces, presented in a fully branded box. Built for the short list of recipients where the gift is expected to look considered.",
    category: "corporate",
    segments: ["csr-corporate-gifts"],
    image: "/images/products/product-spread-grass.jpg",
    purchasable: false,
    moq: "From 100 sets",
    leadTime: "10–15 working days",
    features: ["Seed-paper diary + calendar included", "Fully branded presentation box", "Delivery scheduled with you"],
    featured: true,
  },
];
